version: '3.1'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
